
#Common properties
spring:
  datasource:
    url: 'jdbc:postgresql://${DB_HOST:localhost}:${DB_HOST_PORT:5433}/${APP_DB_NAME:InTouch}'
    username: '${DB_USERNAME}'
    password: '${DB_PASSWORD}'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update #update for production and create-drop for dev
    show-sql: true #false better
    properties:
      hibernate:
      format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: ali
    password: ali
    properties:
      mail:
      smtp:
      trust: "*"
      auth: true
      starttls:
      enabled: true
      connection-timeout: 5000
      timeout: 3000
      write-timeout: 5000

#Custom properties
application:
  security:
    jwt:
      secret_key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh_token:
        expiration: 604800000 # 7 days
  mailing:
    frontend:
      activation_url: http://localhost:8081/activate-account
  messages:
    contactus:
      email: "support@amail.com"
      username:
  aws:
    s3:
      access_key: '${AWS_S3_ACCESS_KEY}'
      secret_key: '${AWS_S3_SECRETE_KEY}'
      bucket_name: intouch-s3-file-upload-bucket
