
#Common properties
#server:
#  ssl:
#    enabled: true
#    key-store: '${KEYSTORE_LOCATION}'
#    key-store-password: '${KEY_STORE_PASSWORD}'
#    key-store-type: PKCS12
#    key-alias: backend
spring:
  datasource:
    url: 'jdbc:postgresql://${DB_HOST:localhost}:${DB_HOST_PORT:5433}/${APP_DB_NAME:InTouch}'
    username: '${DB_USERNAME}'
    password: '${DB_PASSWORD}'
    hikari:
      schema: '${SPRING_DATASOURCE_SCHEMA:intouchappsschema}' #please keep schema name as lower case
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto:  '${JPA_HIBERNATE_DDL_AUTO:create-drop}' #validate for validating create-drop for dev and update for prod
    show-sql: false #false better
    properties:
      hibernate:
        default_schema: '${SPRING_DATASOURCE_DEFAULT_SCHEMA:intouchappsschema}' #please keep schema name as lower case
      format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: '${SPRING_MAIL_HOST:smtp.gmail.com}'
    port: '${SPRING_MAIL_PORT:587}'
    username: '${SPRING_MAIL_USERNAME:dessale4@gmail.com}'
    password: '${SPRING_MAIL_PASSWORD}'
    properties:
      mail:
        smtp:
    #      trust: "*"
          auth: true
          starttls:
            enabled: true
            required: true
            timeout: 3000
      write timeout: 5000
      connection-timeout: 5000

#Custom properties
application:
  security:
    jwt:
      secret_key: '${APPLICATION_SECURITY_JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}'
      expiration:  '${APPLICATION_SECURITY_JWT_SECRET_KEY_EXPIRATION:86400000}' #   a day
#      expiration:  60000 #  1 minute for testing
#      expiration: 5000 #  5 seconds for testing
      refresh_token:
        secret_key: '${APPLICATION_SECURITY_JWT_REFRESH_SECRET_KEY:404E635266556A586E3272357538786876862F413F4428472B4B6250645367566B5970}'
        expiration: '${APPLICATION_SECURITY_JWT_REFRESH_SECRET_KEY_EXPIRATION:259200000}' # 3 days
#        expiration:  60000 #  1 minute for testing
#        expiration: 10000 # 10 seconds for test
  encryption:
    jasyptEncryptionAlgorithm: '${JASYPT_ENCRYPTION_ALGORITHM:PBEWithMD5AndDES}'
    jasyptEncryptionPassword: '${JASYPT_ENCRYPTION_PASSWORD:jasyptPassword}'
    jasyptEncryptionSaltGeneratorClassName: '${JASYPT_ENCRYPTION_SALT_GENERATOR_CLASS_NAME:ZeroSaltGenerator}'
    jasyptIvGeneratorClassName: '${JASYPT_ENCRYPTION_IV_GENERATOR_CLASS_NAME:NoIvGenerator}'
  mailing:
    frontend:
      activation_url: '/${API_CONTEXT_PATH:intouchApi}/v1/auth/activate-account'
    backend:
      email_validation_key: '${EMAIL_VALIDATION_KEY:validateEmail}'
      password_reset_key: '${PASSWORD_RESET_KEY:resetPassword}'
      account_delete_key: '${ACCOUNT_DELETE_KEY:deleteAccount}'
  messages:
    contactus:
      email: '${APP_SUPPORT_EMAIL:support@amail.com}'
      username:
  aws:
    s3:
      access_key: '${AWS_S3_ACCESS_KEY}'
      secret_key: '${AWS_S3_SECRETE_KEY}'
      bucket_name: '${AWS_S3_BUCKET_NAME:intouch-s3-file-upload-bucket}'